### ISSUE TITLE
Question about rendering of the pre-trained nerfh model

### ISSUE THREAD

**Issue by Tausc** [ActiveVisionLab/DFNet#10]
Hello! Thank you for your contribution!
I've loaded your pre-trained nerfH model, but i meet some problem when rendering new image with it:
![0](https://user-images.githubusercontent.com/50770432/222451446-9d246ce3-c4c2-4866-8298-74d23816bbac.png)

while the real-world image looks like:
![frame-000000 color](https://user-images.githubusercontent.com/50770432/222451307-b0fd164a-6df0-4696-ac46-f6e42f78f372.png)

Do you know why this situation is happening?

**Comment by chenusc11** [comment]
Hi, I think this looks like this file has not been properly load. [DFNet](https://github.com/ActiveVisionLab/DFNet)/[data](https://github.com/ActiveVisionLab/DFNet/tree/main/data)/[7Scenes](https://github.com/ActiveVisionLab/DFNet/tree/main/data/7Scenes)/chess/[pose_avg_stats.txt](https://github.com/ActiveVisionLab/DFNet/blob/main/data/7Scenes/chess/pose_avg_stats.txt)

Could you please check if you have put the pose_avg_stats.txt into the 7scene folder?

**Comment by Tausc** [comment]
Thank you for replying!
So I add the pose_avg_stats.txt and function fix_coord() into my rendering code, but i still get some weird rendered images. I read relative code using pose_avg_stats.txt. It seems like this file is used to adjust the input pose. How could it improve the rendered images?

**Comment by chenusc11** [comment]
If I remember this correctly, this is due to the position encoding of the NeRF. Since the query positions of each ray are embedded by the Fourier function (P.E. like Transformer, see NeRF paper), the input xyz values have to be within +- pi. fix_coord() ensures all query ray positions are within this range.

**Comment by chenusc11** [comment]
Sorry. I misread your question. To improve the rendered image, you might use a better "ground truth pose" other than the dataset provided ones. Say COLMAP.
The reason is the current GT poses are provided by depth-based slam, which in nature is a bit off-sync with the RGB images. Therefore, the rendering quality is not as good.

**Comment by Tausc** [comment]
So the poor rendering results is caused because the input pose and histogram do not match when calling the rendering function? Is there any problem with this understanding?

**Comment by chenusc11** [comment]
Hi, really sorry for the late reply. I was on a leave due to family issue. 

Have you solved your problem? If not, we could follow up your problem via email. I'm not exactly sure what you mean by “weird rendered images”. Maybe send me some of your examples?

**Comment by chenusc11** [comment]
Close the issue for now. Feel free to re-open it if there's further question
