### ISSUE TITLE
How to get setup_world.json for a new dataset?

### ISSUE THREAD

**Issue by shenyehui** [ActiveVisionLab/DFNet#22]
Dear author, I want to train nerf-h using my dataset. However, it only have transformer.json, how can i get setup_world.json for it?

**Comment by chenusc11** [comment]
Hi, setup_world.json is a manually tuned hyperparameters, as explained in [here](https://github.com/ActiveVisionLab/DFNet/issues/21). What I did, was to write a script to visualize the camera rays from my dataset's camera poses and manually adjust the scenes to center at (0,0,0) (for example, using move_all_cam_vec), and rescale the camera rays to within [-pi, pi]

**Comment by PAU1G3ORGE** [comment]
I'd appreciate it if I could consult your script for guidance.

**Comment by chenusc11** [comment]
Hi, @PAU1G3ORGE I don't have the python notebook script left because it has been quite a while. However, it is not very hard to rewrite the code. I think I used this code here to convert the camera pose into camera rays.

[pose_to_ray.txt](https://github.com/user-attachments/files/18242131/pose_to_ray.txt)

Once you convert your camera pose into camera rays, you can use matplotlib or some plotting library to draw them in the 3D space.

Hope this helps.

**Comment by PAU1G3ORGE** [comment]
Thanks a lot!
